# Job from R2Devops hub --> r2devops.io

stages:
  - tests

ng_lint:

  image:
    name: node:${IMAGE_TAG}
    entrypoint: [""]

  stage: tests

  variables:
    PROJECT_ROOT: "."
    PROJECT_NAME: ""
    NG_LINT_OPTIONS: ""
    NG_LINT_PACKAGE: ""

    IMAGE_TAG: "18-buster"
  script:
    - cd ${PROJECT_ROOT}
    - npm install
    - npm install -g @angular/cli
    - |
      if [[ ${NG_LINT_PACKAGE} != "" ]]; then
      ng add ${NG_LINT_PACKAGE}
      fi
    - ng lint ${PROJECT_NAME} ${NG_LINT_OPTIONS}
