# Job from R2Devops hub --> r2devops.io

stages:
  - build

yarn_build:
  stage: build
  image:
    name: node:${IMAGE_TAG}
    entrypoint: [""]
  variables:
    PROJECT_ROOT: "."
    YARN_INSTALL_OPTIONS: ""
    YARN_BUILD_SCRIPT_NAME: "build"
    YARN_BUILD_OPTIONS: ""
    YARN_BUILD_OUTPUT_FOLDER: "build"
    PAGES_FOLDER: "./website_build"
    IMAGE_TAG: "18-buster"
  script:
    # Working directory
    - cd $PROJECT_ROOT
    - yarn install $YARN_INSTALL_OPTIONS
    - yarn run $YARN_BUILD_SCRIPT_NAME $YARN_BUILD_OPTIONS
    # Pages folder must to be at the root of the repo
    - cd $CI_PROJECT_DIR
    - cp -r ${PROJECT_ROOT}/${YARN_BUILD_OUTPUT_FOLDER} ${CI_PROJECT_DIR}/${PAGES_FOLDER}
  artifacts:
    expose_as: "yarn build"
    paths:
      - "${PROJECT_ROOT}/${YARN_BUILD_OUTPUT_FOLDER}"
      - "${PAGES_FOLDER}"
      # Below path is a workaround to provide artifact exposition in MR if
      # default value is used. See https://r2devops.io/jobs/build/yarn_build/#artifact
      - "build/"
